version: '3'

services:
  app:
    container_name: lunafreya-server_app
    image: apquinit/adonisjs:latest
    ports:
      - '3333:3333'
    volumes:
      - $PWD:/var/www
    depends_on:
      - database
    networks:
      - network

  database:
    container_name: lunafreya-server_database
    image: postgres:12.0
    ports:
      - '5432:5432'
    volumes:
      - $PWD/database/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lunafreya
    networks:
      - network

networks:
  network:
    driver: bridge